    services:
  - type: cron
    name: deusinstagram-06h
    repo: https://github.com/klebertanide/deus
    schedule: '0 6 * * *' # Executa às 06:00 UTC
    envVars:
      - key: OPENAI_API_KEY
        value: valor
    startCommand: python main.py

  - type: cron
    name: deusinstagram-18h
    repo: https://github.com/klebertanide/deus
    schedule: '0 18 * * *' # Executa às 18:00 UTC
    envVars:
      - key: OPENAI_API_KEY
        value: valor
    startCommand: python main.py
